# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2NmYTkwODgyODQ0NWRhNzE0NmE0NThjMzM5YTFlMTVlZTNlZjIzMDBjZmNmNTEyZGY1ZTAxZWE3NDQxM2YzMzI0OGY4ZDk1ZDBhOWEwOGE1ZTllYjQ1NDM1ZWFjMjc0NmRhOThkNjdhMTcwZTU3ZTkzMTk0ZjRmNTQyMDUyZmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
